// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SignupRequest signup request
//
// swagger:model SignupRequest
type SignupRequest struct {

	// User's email
	// Example: js@example.org
	Email string `json:"email,omitempty"`

	// User's first name
	// Example: John
	Firstname string `json:"firstname,omitempty"`

	// User's last name
	// Example: Smith
	Lastname string `json:"lastname,omitempty"`

	// User's password
	// Example: some_password
	Password string `json:"password,omitempty"`
}

// Validate validates this signup request
func (m *SignupRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this signup request based on context it is used
func (m *SignupRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignupRequest) UnmarshalBinary(b []byte) error {
	var res SignupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
