version: "2"

linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - revive
    - gosec
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - misspell

  settings:
    gosec:
      excludes:
        - G115 # Annoying and have a lot of false-positive results.
    govet:
      enable:
        - shadow
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
        - appendAssign
        - unnecessaryBlock
        - redundantSprint
        - octalLiteral
        - ifElseChain
        - paramTypeCombine

  exclusions:
    rules:
      # Document when API is stable
      - text: "should have comment"
        linters: [revive]

      # Disable linters that are annoying in tests.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
          - goconst
          - gocognit
          - lll

      - path: _test\.go
        text: "Combine"
        linters:
          - gocritic

      # Check that equal to self is true
      - linters: [gocritic]
        source: '(assert|require).+Equal'
        text: 'dupArg'
        path: _test\.go

      # Ignore shadowing of err.
      - linters: [govet]
        text: 'declaration of "(err|ctx|log|lg|c)"'

      # Ignore linters in main packages.
      - path: main\.go
        linters: [goconst, funlen, gocognit, gocyclo]

      - path: main\.go
        linters: [gosec]
        text: "G307"

      # Probably some broken linter for generics?
      - linters: [revive]
        text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'

      - source: 'func Fuzz.+\(f \*testing\.F\)'
        linters: [stylecheck]
        text: "ST1003" # underscores lol

      - path: (internal|grpcservice)
        linters: [revive]
        text: "package-comments"

      - linters: [revive]
        text: "comment on exported const .+ should be of the form"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports: {}

  exclusions:
    paths:
      - _test\.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # Do not enable:
  # - wsl       (too opinionated about newlines)
  # - godox     (todos are OK)
  # - bodyclose (false positives on helper functions)
  # - funlen    (gocyclo is enough)
  # - gochecknoglobals (we know when it is ok to use globals)
  # - dupl      (threshold: 120)
  # - lll       (line-length: 140)
  # - gocyclo   (min-complexity: 15)
