// Code generated by go-swagger; DO NOT EDIT.

package signup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSignupHandlerFunc turns a function with the right signature into a post signup handler
type PostSignupHandlerFunc func(PostSignupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSignupHandlerFunc) Handle(params PostSignupParams) middleware.Responder {
	return fn(params)
}

// PostSignupHandler interface for that can handle valid post signup params
type PostSignupHandler interface {
	Handle(PostSignupParams) middleware.Responder
}

// NewPostSignup creates a new http.Handler for the post signup operation
func NewPostSignup(ctx *middleware.Context, handler PostSignupHandler) *PostSignup {
	return &PostSignup{Context: ctx, Handler: handler}
}

/*
	PostSignup swagger:route POST /signup Signup postSignup

Sign-up request
*/
type PostSignup struct {
	Context *middleware.Context
	Handler PostSignupHandler
}

func (o *PostSignup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSignupParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
