// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcceptEndGame implements acceptEndGame operation.
//
// The opponent accepts the end-game proposal. The game ends immediately with the current scores. Only
// the non-proposing player may call this.
//
// POST /games/{id}/accept-end
func (UnimplementedHandler) AcceptEndGame(ctx context.Context, params AcceptEndGameParams) (r AcceptEndGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Auth implements auth operation.
//
// Auth request.
//
// POST /auth
func (UnimplementedHandler) Auth(ctx context.Context, req *AuthRequest) (r AuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthTelegram implements authTelegram operation.
//
// Validates the signed init data produced by the Telegram WebView against the bot token, then logs in
// an existing user or creates a new one linked to their Telegram account.
//
// POST /auth/telegram
func (UnimplementedHandler) AuthTelegram(ctx context.Context, req *TelegramAuthRequest) (r AuthTelegramRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGame implements createGame operation.
//
// Create a new game.
//
// POST /games
func (UnimplementedHandler) CreateGame(ctx context.Context) (r CreateGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGameWithBot implements createGameWithBot operation.
//
// Creates a new game where the authenticated player plays against a server-side bot. The game starts
// immediately and the first move belongs to the human player.
//
// POST /games/with-bot
func (UnimplementedHandler) CreateGameWithBot(ctx context.Context) (r CreateGameWithBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfig implements getConfig operation.
//
// Returns feature flags the client needs before authentication, e.g. whether email/password
// registration is available.
//
// GET /config
func (UnimplementedHandler) GetConfig(ctx context.Context) (r *ConfigResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLeaderboard implements getLeaderboard operation.
//
// Returns the top players by current rating or total EXP who were active during the requested period.
// Results are cached for 5 minutes.
//
// GET /leaderboard
func (UnimplementedHandler) GetLeaderboard(ctx context.Context, params GetLeaderboardParams) (r GetLeaderboardRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerAchievements implements getPlayerAchievements operation.
//
// Returns the full list of achievements with their unlocked status for the currently authenticated
// player.
//
// GET /player/achievements
func (UnimplementedHandler) GetPlayerAchievements(ctx context.Context) (r GetPlayerAchievementsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerStateUID implements getPlayerStateUID operation.
//
// Get user state.
//
// GET /player/state/{uid}
func (UnimplementedHandler) GetPlayerStateUID(ctx context.Context, params GetPlayerStateUIDParams) (r GetPlayerStateUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerStats implements getPlayerStats operation.
//
// Returns lifetime aggregated statistics for the currently authenticated player: games played,
// wins/losses/draws, win rate, average word length, best word and favorite letter.
//
// GET /player/stats
func (UnimplementedHandler) GetPlayerStats(ctx context.Context) (r GetPlayerStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// JoinGame implements joinGame operation.
//
// Adds the authenticated player to the specified waiting game. When the second player joins (quorum of
// 2 is reached) the game transitions to in_progress and the first move belongs to the player who
// created the game.
//
// POST /games/{id}/join
func (UnimplementedHandler) JoinGame(ctx context.Context, params JoinGameParams) (r JoinGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGames implements listGames operation.
//
// Returns a snapshot of all currently active games.
//
// GET /games
func (UnimplementedHandler) ListGames(ctx context.Context) (r ListGamesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Revoke the current refresh token.
//
// POST /auth/logout
func (UnimplementedHandler) Logout(ctx context.Context, req OptLogoutRequest) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MatchmakingJoin implements matchmakingJoin operation.
//
// Enqueues the player for quick matchmaking. When a human opponent with a close rating is found, a
// match_found event is published to the lobby channel; after a timeout the server starts a bot game.
//
// POST /matchmaking/join
func (UnimplementedHandler) MatchmakingJoin(ctx context.Context) (r MatchmakingJoinRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MatchmakingLeave implements matchmakingLeave operation.
//
// Idempotent — leaving without being queued is not an error.
//
// POST /matchmaking/leave
func (UnimplementedHandler) MatchmakingLeave(ctx context.Context) (r MatchmakingLeaveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MoveGame implements moveGame operation.
//
// Places a new letter on the board and submits a word. If the word is valid, the player's score is
// updated and the turn passes to the opponent.
//
// POST /games/{id}/move
func (UnimplementedHandler) MoveGame(ctx context.Context, req *MoveRequest, params MoveGameParams) (r MoveGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// POST not GET — mutates session TTL. Returns 204 with X-Server-Time header instead of a JSON body
// to minimize bandwidth on frequent pings (every ping_delay ms).
//
// POST /session/ping
func (UnimplementedHandler) Ping(ctx context.Context, params PingParams) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProposeEndGame implements proposeEndGame operation.
//
// The current player proposes to end the game (e.g. no valid moves are available). The turn timer is
// paused until the opponent responds. Only the player whose turn it currently is may call this.
//
// POST /games/{id}/propose-end
func (UnimplementedHandler) ProposeEndGame(ctx context.Context, params ProposeEndGameParams) (r ProposeEndGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshToken implements refreshToken operation.
//
// Exchange a refresh token for a new access/refresh pair.
//
// POST /auth/refresh
func (UnimplementedHandler) RefreshToken(ctx context.Context, req *RefreshRequest) (r RefreshTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RejectEndGame implements rejectEndGame operation.
//
// The opponent rejects the end-game proposal. The game resumes with the remaining turn time (minimum
// 10 seconds). Only the non-proposing player may call this.
//
// POST /games/{id}/reject-end
func (UnimplementedHandler) RejectEndGame(ctx context.Context, params RejectEndGameParams) (r RejectEndGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Signup implements signup operation.
//
// Sign-up request.
//
// POST /signup
func (UnimplementedHandler) Signup(ctx context.Context, req *SignupRequest) (r SignupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SkipGame implements skipGame operation.
//
// Ends the current turn without making a move. The turn passes to the opponent.
//
// POST /games/{id}/skip
func (UnimplementedHandler) SkipGame(ctx context.Context, params SkipGameParams) (r SkipGameRes, _ error) {
	return r, ht.ErrNotImplemented
}
