// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type AcceptEndGameConflict ErrorResponse

func (*AcceptEndGameConflict) acceptEndGameRes() {}

type AcceptEndGameForbidden ErrorResponse

func (*AcceptEndGameForbidden) acceptEndGameRes() {}

// AcceptEndGameNoContent is response for AcceptEndGame operation.
type AcceptEndGameNoContent struct{}

func (*AcceptEndGameNoContent) acceptEndGameRes() {}

type AcceptEndGameNotFound ErrorResponse

func (*AcceptEndGameNotFound) acceptEndGameRes() {}

type AcceptEndGameUnauthorized ErrorResponse

func (*AcceptEndGameUnauthorized) acceptEndGameRes() {}

// Ref: #/components/schemas/Achievement
type Achievement struct {
	// Achievement identifier.
	ID OptAchievementID `json:"id"`
	// Achievement display name.
	Name OptString `json:"name"`
	// Achievement description.
	Description OptString `json:"description"`
	// Whether the achievement has been unlocked.
	Unlocked OptBool `json:"unlocked"`
}

// GetID returns the value of ID.
func (s *Achievement) GetID() OptAchievementID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Achievement) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Achievement) GetDescription() OptString {
	return s.Description
}

// GetUnlocked returns the value of Unlocked.
func (s *Achievement) GetUnlocked() OptBool {
	return s.Unlocked
}

// SetID sets the value of ID.
func (s *Achievement) SetID(val OptAchievementID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Achievement) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Achievement) SetDescription(val OptString) {
	s.Description = val
}

// SetUnlocked sets the value of Unlocked.
func (s *Achievement) SetUnlocked(val OptBool) {
	s.Unlocked = val
}

// Achievement identifier.
type AchievementID string

const (
	AchievementIDFirstGame      AchievementID = "first_game"
	AchievementIDFirstWin       AchievementID = "first_win"
	AchievementIDHighScorer50   AchievementID = "high_scorer_50"
	AchievementIDWordsmith10    AchievementID = "wordsmith_10"
	AchievementIDGiantWord      AchievementID = "giant_word"
	AchievementIDWinningStreak3 AchievementID = "winning_streak_3"
	AchievementIDVeteran10      AchievementID = "veteran_10"
)

// AllValues returns all AchievementID values.
func (AchievementID) AllValues() []AchievementID {
	return []AchievementID{
		AchievementIDFirstGame,
		AchievementIDFirstWin,
		AchievementIDHighScorer50,
		AchievementIDWordsmith10,
		AchievementIDGiantWord,
		AchievementIDWinningStreak3,
		AchievementIDVeteran10,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AchievementID) MarshalText() ([]byte, error) {
	switch s {
	case AchievementIDFirstGame:
		return []byte(s), nil
	case AchievementIDFirstWin:
		return []byte(s), nil
	case AchievementIDHighScorer50:
		return []byte(s), nil
	case AchievementIDWordsmith10:
		return []byte(s), nil
	case AchievementIDGiantWord:
		return []byte(s), nil
	case AchievementIDWinningStreak3:
		return []byte(s), nil
	case AchievementIDVeteran10:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AchievementID) UnmarshalText(data []byte) error {
	switch AchievementID(data) {
	case AchievementIDFirstGame:
		*s = AchievementIDFirstGame
		return nil
	case AchievementIDFirstWin:
		*s = AchievementIDFirstWin
		return nil
	case AchievementIDHighScorer50:
		*s = AchievementIDHighScorer50
		return nil
	case AchievementIDWordsmith10:
		*s = AchievementIDWordsmith10
		return nil
	case AchievementIDGiantWord:
		*s = AchievementIDGiantWord
		return nil
	case AchievementIDWinningStreak3:
		*s = AchievementIDWinningStreak3
		return nil
	case AchievementIDVeteran10:
		*s = AchievementIDVeteran10
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ActiveGame
type ActiveGame struct {
	// ID of the active game.
	GameID OptUUID `json:"game_id"`
	// Centrifugo subscription JWT for the game channel.
	GameToken OptString `json:"game_token"`
	// Current 5x5 board state.
	Board [][]string `json:"board"`
	// ID of the player whose turn it is.
	CurrentTurnUID OptUUID           `json:"current_turn_uid"`
	MoveNumber     OptInt            `json:"move_number"`
	Status         OptGameStatus     `json:"status"`
	Players        []PlayerGameState `json:"players"`
}

// GetGameID returns the value of GameID.
func (s *ActiveGame) GetGameID() OptUUID {
	return s.GameID
}

// GetGameToken returns the value of GameToken.
func (s *ActiveGame) GetGameToken() OptString {
	return s.GameToken
}

// GetBoard returns the value of Board.
func (s *ActiveGame) GetBoard() [][]string {
	return s.Board
}

// GetCurrentTurnUID returns the value of CurrentTurnUID.
func (s *ActiveGame) GetCurrentTurnUID() OptUUID {
	return s.CurrentTurnUID
}

// GetMoveNumber returns the value of MoveNumber.
func (s *ActiveGame) GetMoveNumber() OptInt {
	return s.MoveNumber
}

// GetStatus returns the value of Status.
func (s *ActiveGame) GetStatus() OptGameStatus {
	return s.Status
}

// GetPlayers returns the value of Players.
func (s *ActiveGame) GetPlayers() []PlayerGameState {
	return s.Players
}

// SetGameID sets the value of GameID.
func (s *ActiveGame) SetGameID(val OptUUID) {
	s.GameID = val
}

// SetGameToken sets the value of GameToken.
func (s *ActiveGame) SetGameToken(val OptString) {
	s.GameToken = val
}

// SetBoard sets the value of Board.
func (s *ActiveGame) SetBoard(val [][]string) {
	s.Board = val
}

// SetCurrentTurnUID sets the value of CurrentTurnUID.
func (s *ActiveGame) SetCurrentTurnUID(val OptUUID) {
	s.CurrentTurnUID = val
}

// SetMoveNumber sets the value of MoveNumber.
func (s *ActiveGame) SetMoveNumber(val OptInt) {
	s.MoveNumber = val
}

// SetStatus sets the value of Status.
func (s *ActiveGame) SetStatus(val OptGameStatus) {
	s.Status = val
}

// SetPlayers sets the value of Players.
func (s *ActiveGame) SetPlayers(val []PlayerGameState) {
	s.Players = val
}

// Ref: #/components/schemas/AuthRequest
type AuthRequest struct {
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *AuthRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *AuthRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *AuthRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *AuthRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	Player OptPlayer `json:"player"`
	// Short-lived JWT access token (Authorization:&nbsp;Bearer).
	AccessToken OptString `json:"access_token"`
	// Opaque long-lived token used to obtain a new access token.
	RefreshToken OptString `json:"refresh_token"`
	// Always "Bearer".
	TokenType OptString `json:"token_type"`
	// Access token lifetime in seconds.
	ExpiresIn OptInt `json:"expires_in"`
	// JWT for connecting to the Centrifugo WebSocket.
	CentrifugoToken OptString `json:"centrifugo_token"`
	// Centrifugo subscription JWT for the lobby channel.
	LobbyToken OptString `json:"lobby_token"`
	// Present when the player is currently in an active game. Use this to reconnect after a disconnect.
	ActiveGame OptActiveGame `json:"active_game"`
}

// GetPlayer returns the value of Player.
func (s *AuthResponse) GetPlayer() OptPlayer {
	return s.Player
}

// GetAccessToken returns the value of AccessToken.
func (s *AuthResponse) GetAccessToken() OptString {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *AuthResponse) GetRefreshToken() OptString {
	return s.RefreshToken
}

// GetTokenType returns the value of TokenType.
func (s *AuthResponse) GetTokenType() OptString {
	return s.TokenType
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *AuthResponse) GetExpiresIn() OptInt {
	return s.ExpiresIn
}

// GetCentrifugoToken returns the value of CentrifugoToken.
func (s *AuthResponse) GetCentrifugoToken() OptString {
	return s.CentrifugoToken
}

// GetLobbyToken returns the value of LobbyToken.
func (s *AuthResponse) GetLobbyToken() OptString {
	return s.LobbyToken
}

// GetActiveGame returns the value of ActiveGame.
func (s *AuthResponse) GetActiveGame() OptActiveGame {
	return s.ActiveGame
}

// SetPlayer sets the value of Player.
func (s *AuthResponse) SetPlayer(val OptPlayer) {
	s.Player = val
}

// SetAccessToken sets the value of AccessToken.
func (s *AuthResponse) SetAccessToken(val OptString) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *AuthResponse) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

// SetTokenType sets the value of TokenType.
func (s *AuthResponse) SetTokenType(val OptString) {
	s.TokenType = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *AuthResponse) SetExpiresIn(val OptInt) {
	s.ExpiresIn = val
}

// SetCentrifugoToken sets the value of CentrifugoToken.
func (s *AuthResponse) SetCentrifugoToken(val OptString) {
	s.CentrifugoToken = val
}

// SetLobbyToken sets the value of LobbyToken.
func (s *AuthResponse) SetLobbyToken(val OptString) {
	s.LobbyToken = val
}

// SetActiveGame sets the value of ActiveGame.
func (s *AuthResponse) SetActiveGame(val OptActiveGame) {
	s.ActiveGame = val
}

func (*AuthResponse) authRes()         {}
func (*AuthResponse) authTelegramRes() {}

type AuthTelegramInternalServerError ErrorResponse

func (*AuthTelegramInternalServerError) authTelegramRes() {}

type AuthTelegramServiceUnavailable ErrorResponse

func (*AuthTelegramServiceUnavailable) authTelegramRes() {}

type AuthTelegramUnauthorized ErrorResponse

func (*AuthTelegramUnauthorized) authTelegramRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// A cell position on the 5×5 board, used in word_path. The character at each cell is resolved
// server-side from the current board state; clients do not need to send it. The new letter being
// placed is provided separately in new_letter.char.
// Ref: #/components/schemas/BoardCell
type BoardCell struct {
	Row int `json:"row"`
	Col int `json:"col"`
}

// GetRow returns the value of Row.
func (s *BoardCell) GetRow() int {
	return s.Row
}

// GetCol returns the value of Col.
func (s *BoardCell) GetCol() int {
	return s.Col
}

// SetRow sets the value of Row.
func (s *BoardCell) SetRow(val int) {
	s.Row = val
}

// SetCol sets the value of Col.
func (s *BoardCell) SetCol(val int) {
	s.Col = val
}

// Ref: #/components/schemas/ConfigResponse
type ConfigResponse struct {
	// Whether email/password registration is available.
	EmailSignupEnabled OptBool `json:"email_signup_enabled"`
}

// GetEmailSignupEnabled returns the value of EmailSignupEnabled.
func (s *ConfigResponse) GetEmailSignupEnabled() OptBool {
	return s.EmailSignupEnabled
}

// SetEmailSignupEnabled sets the value of EmailSignupEnabled.
func (s *ConfigResponse) SetEmailSignupEnabled(val OptBool) {
	s.EmailSignupEnabled = val
}

// Ref: #/components/schemas/CreateGameResponse
type CreateGameResponse struct {
	Game OptGameSummary `json:"game"`
	// Centrifugo subscription JWT for the game channel.
	GameToken OptString `json:"game_token"`
}

// GetGame returns the value of Game.
func (s *CreateGameResponse) GetGame() OptGameSummary {
	return s.Game
}

// GetGameToken returns the value of GameToken.
func (s *CreateGameResponse) GetGameToken() OptString {
	return s.GameToken
}

// SetGame sets the value of Game.
func (s *CreateGameResponse) SetGame(val OptGameSummary) {
	s.Game = val
}

// SetGameToken sets the value of GameToken.
func (s *CreateGameResponse) SetGameToken(val OptString) {
	s.GameToken = val
}

func (*CreateGameResponse) createGameRes() {}

type CreateGameWithBotConflict ErrorResponse

func (*CreateGameWithBotConflict) createGameWithBotRes() {}

type CreateGameWithBotInternalServerError ErrorResponse

func (*CreateGameWithBotInternalServerError) createGameWithBotRes() {}

type CreateGameWithBotUnauthorized ErrorResponse

func (*CreateGameWithBotUnauthorized) createGameWithBotRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// The HTTP response code.
	Status OptInt `json:"status"`
	// A human-readable explanation of the error.
	Message OptString `json:"message"`
	// Type of the error message.
	Type OptString `json:"type"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() OptInt {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() OptString {
	return s.Message
}

// GetType returns the value of Type.
func (s *ErrorResponse) GetType() OptString {
	return s.Type
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val OptInt) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetType sets the value of Type.
func (s *ErrorResponse) SetType(val OptString) {
	s.Type = val
}

func (*ErrorResponse) authRes()         {}
func (*ErrorResponse) createGameRes()   {}
func (*ErrorResponse) listGamesRes()    {}
func (*ErrorResponse) logoutRes()       {}
func (*ErrorResponse) pingRes()         {}
func (*ErrorResponse) refreshTokenRes() {}
func (*ErrorResponse) signupRes()       {}

// Current state of the game.
// Ref: #/components/schemas/GameStatus
type GameStatus string

const (
	GameStatusWaiting    GameStatus = "waiting"
	GameStatusInProgress GameStatus = "in_progress"
	GameStatusFinished   GameStatus = "finished"
)

// AllValues returns all GameStatus values.
func (GameStatus) AllValues() []GameStatus {
	return []GameStatus{
		GameStatusWaiting,
		GameStatusInProgress,
		GameStatusFinished,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GameStatus) MarshalText() ([]byte, error) {
	switch s {
	case GameStatusWaiting:
		return []byte(s), nil
	case GameStatusInProgress:
		return []byte(s), nil
	case GameStatusFinished:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GameStatus) UnmarshalText(data []byte) error {
	switch GameStatus(data) {
	case GameStatusWaiting:
		*s = GameStatusWaiting
		return nil
	case GameStatusInProgress:
		*s = GameStatusInProgress
		return nil
	case GameStatusFinished:
		*s = GameStatusFinished
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/GameSummary
type GameSummary struct {
	// Game ID.
	ID OptUUID `json:"id"`
	// IDs of players participating in the game.
	PlayerIds []uuid.UUID `json:"player_ids"`
	// Players with EXP info.
	Players []LobbyPlayer `json:"players"`
	Status  OptGameStatus `json:"status"`
	// When the game was started (Unix timestamp in milliseconds).
	StartedAt OptInt64 `json:"started_at"`
}

// GetID returns the value of ID.
func (s *GameSummary) GetID() OptUUID {
	return s.ID
}

// GetPlayerIds returns the value of PlayerIds.
func (s *GameSummary) GetPlayerIds() []uuid.UUID {
	return s.PlayerIds
}

// GetPlayers returns the value of Players.
func (s *GameSummary) GetPlayers() []LobbyPlayer {
	return s.Players
}

// GetStatus returns the value of Status.
func (s *GameSummary) GetStatus() OptGameStatus {
	return s.Status
}

// GetStartedAt returns the value of StartedAt.
func (s *GameSummary) GetStartedAt() OptInt64 {
	return s.StartedAt
}

// SetID sets the value of ID.
func (s *GameSummary) SetID(val OptUUID) {
	s.ID = val
}

// SetPlayerIds sets the value of PlayerIds.
func (s *GameSummary) SetPlayerIds(val []uuid.UUID) {
	s.PlayerIds = val
}

// SetPlayers sets the value of Players.
func (s *GameSummary) SetPlayers(val []LobbyPlayer) {
	s.Players = val
}

// SetStatus sets the value of Status.
func (s *GameSummary) SetStatus(val OptGameStatus) {
	s.Status = val
}

// SetStartedAt sets the value of StartedAt.
func (s *GameSummary) SetStartedAt(val OptInt64) {
	s.StartedAt = val
}

type GetLeaderboardBadRequest ErrorResponse

func (*GetLeaderboardBadRequest) getLeaderboardRes() {}

type GetLeaderboardInternalServerError ErrorResponse

func (*GetLeaderboardInternalServerError) getLeaderboardRes() {}

type GetLeaderboardPeriod string

const (
	GetLeaderboardPeriodWeek  GetLeaderboardPeriod = "week"
	GetLeaderboardPeriodMonth GetLeaderboardPeriod = "month"
)

// AllValues returns all GetLeaderboardPeriod values.
func (GetLeaderboardPeriod) AllValues() []GetLeaderboardPeriod {
	return []GetLeaderboardPeriod{
		GetLeaderboardPeriodWeek,
		GetLeaderboardPeriodMonth,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetLeaderboardPeriod) MarshalText() ([]byte, error) {
	switch s {
	case GetLeaderboardPeriodWeek:
		return []byte(s), nil
	case GetLeaderboardPeriodMonth:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetLeaderboardPeriod) UnmarshalText(data []byte) error {
	switch GetLeaderboardPeriod(data) {
	case GetLeaderboardPeriodWeek:
		*s = GetLeaderboardPeriodWeek
		return nil
	case GetLeaderboardPeriodMonth:
		*s = GetLeaderboardPeriodMonth
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetLeaderboardSort string

const (
	GetLeaderboardSortRating GetLeaderboardSort = "rating"
	GetLeaderboardSortExp    GetLeaderboardSort = "exp"
)

// AllValues returns all GetLeaderboardSort values.
func (GetLeaderboardSort) AllValues() []GetLeaderboardSort {
	return []GetLeaderboardSort{
		GetLeaderboardSortRating,
		GetLeaderboardSortExp,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetLeaderboardSort) MarshalText() ([]byte, error) {
	switch s {
	case GetLeaderboardSortRating:
		return []byte(s), nil
	case GetLeaderboardSortExp:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetLeaderboardSort) UnmarshalText(data []byte) error {
	switch GetLeaderboardSort(data) {
	case GetLeaderboardSortRating:
		*s = GetLeaderboardSortRating
		return nil
	case GetLeaderboardSortExp:
		*s = GetLeaderboardSortExp
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetPlayerAchievementsInternalServerError ErrorResponse

func (*GetPlayerAchievementsInternalServerError) getPlayerAchievementsRes() {}

type GetPlayerAchievementsUnauthorized ErrorResponse

func (*GetPlayerAchievementsUnauthorized) getPlayerAchievementsRes() {}

type GetPlayerStateUIDBadRequest ErrorResponse

func (*GetPlayerStateUIDBadRequest) getPlayerStateUIDRes() {}

type GetPlayerStateUIDForbidden ErrorResponse

func (*GetPlayerStateUIDForbidden) getPlayerStateUIDRes() {}

type GetPlayerStateUIDUnauthorized ErrorResponse

func (*GetPlayerStateUIDUnauthorized) getPlayerStateUIDRes() {}

type GetPlayerStatsInternalServerError ErrorResponse

func (*GetPlayerStatsInternalServerError) getPlayerStatsRes() {}

type GetPlayerStatsUnauthorized ErrorResponse

func (*GetPlayerStatsUnauthorized) getPlayerStatsRes() {}

type JoinGameConflict ErrorResponse

func (*JoinGameConflict) joinGameRes() {}

type JoinGameInternalServerError ErrorResponse

func (*JoinGameInternalServerError) joinGameRes() {}

type JoinGameNotFound ErrorResponse

func (*JoinGameNotFound) joinGameRes() {}

// Ref: #/components/schemas/JoinGameResponse
type JoinGameResponse struct {
	Game OptGameSummary `json:"game"`
	// Centrifugo subscription JWT for the game channel.
	GameToken OptString `json:"game_token"`
	// Initial 5x5 board state. Each row is an array of 5 single-character strings (empty string means
	// empty cell). Included so the joining player can render the board immediately without waiting for the
	// Centrifugo game_state event.
	Board [][]string `json:"board"`
	// ID of the player whose turn it is first (the game creator).
	CurrentTurnUID OptString `json:"current_turn_uid"`
}

// GetGame returns the value of Game.
func (s *JoinGameResponse) GetGame() OptGameSummary {
	return s.Game
}

// GetGameToken returns the value of GameToken.
func (s *JoinGameResponse) GetGameToken() OptString {
	return s.GameToken
}

// GetBoard returns the value of Board.
func (s *JoinGameResponse) GetBoard() [][]string {
	return s.Board
}

// GetCurrentTurnUID returns the value of CurrentTurnUID.
func (s *JoinGameResponse) GetCurrentTurnUID() OptString {
	return s.CurrentTurnUID
}

// SetGame sets the value of Game.
func (s *JoinGameResponse) SetGame(val OptGameSummary) {
	s.Game = val
}

// SetGameToken sets the value of GameToken.
func (s *JoinGameResponse) SetGameToken(val OptString) {
	s.GameToken = val
}

// SetBoard sets the value of Board.
func (s *JoinGameResponse) SetBoard(val [][]string) {
	s.Board = val
}

// SetCurrentTurnUID sets the value of CurrentTurnUID.
func (s *JoinGameResponse) SetCurrentTurnUID(val OptString) {
	s.CurrentTurnUID = val
}

func (*JoinGameResponse) createGameWithBotRes() {}
func (*JoinGameResponse) joinGameRes()          {}

type JoinGameUnauthorized ErrorResponse

func (*JoinGameUnauthorized) joinGameRes() {}

// Ref: #/components/schemas/LeaderboardEntry
type LeaderboardEntry struct {
	// Position in the leaderboard (1-based).
	Rank OptInt `json:"rank"`
	// Player's ID.
	UID OptUUID `json:"uid"`
	// Player's generated nickname.
	Nickname OptString `json:"nickname"`
	// Player's ELO rating.
	Rating OptInt64 `json:"rating"`
	// Player's total EXP.
	Exp OptInt64 `json:"exp"`
}

// GetRank returns the value of Rank.
func (s *LeaderboardEntry) GetRank() OptInt {
	return s.Rank
}

// GetUID returns the value of UID.
func (s *LeaderboardEntry) GetUID() OptUUID {
	return s.UID
}

// GetNickname returns the value of Nickname.
func (s *LeaderboardEntry) GetNickname() OptString {
	return s.Nickname
}

// GetRating returns the value of Rating.
func (s *LeaderboardEntry) GetRating() OptInt64 {
	return s.Rating
}

// GetExp returns the value of Exp.
func (s *LeaderboardEntry) GetExp() OptInt64 {
	return s.Exp
}

// SetRank sets the value of Rank.
func (s *LeaderboardEntry) SetRank(val OptInt) {
	s.Rank = val
}

// SetUID sets the value of UID.
func (s *LeaderboardEntry) SetUID(val OptUUID) {
	s.UID = val
}

// SetNickname sets the value of Nickname.
func (s *LeaderboardEntry) SetNickname(val OptString) {
	s.Nickname = val
}

// SetRating sets the value of Rating.
func (s *LeaderboardEntry) SetRating(val OptInt64) {
	s.Rating = val
}

// SetExp sets the value of Exp.
func (s *LeaderboardEntry) SetExp(val OptInt64) {
	s.Exp = val
}

// Ref: #/components/schemas/LeaderboardResponse
type LeaderboardResponse struct {
	// Leaderboard period.
	Period OptLeaderboardResponsePeriod `json:"period"`
	// Sort field.
	Sort OptLeaderboardResponseSort `json:"sort"`
	// Unix timestamp in milliseconds when the leaderboard was generated.
	GeneratedAt OptInt64 `json:"generated_at"`
	// Leaderboard entries ordered by rank.
	Players []LeaderboardEntry `json:"players"`
}

// GetPeriod returns the value of Period.
func (s *LeaderboardResponse) GetPeriod() OptLeaderboardResponsePeriod {
	return s.Period
}

// GetSort returns the value of Sort.
func (s *LeaderboardResponse) GetSort() OptLeaderboardResponseSort {
	return s.Sort
}

// GetGeneratedAt returns the value of GeneratedAt.
func (s *LeaderboardResponse) GetGeneratedAt() OptInt64 {
	return s.GeneratedAt
}

// GetPlayers returns the value of Players.
func (s *LeaderboardResponse) GetPlayers() []LeaderboardEntry {
	return s.Players
}

// SetPeriod sets the value of Period.
func (s *LeaderboardResponse) SetPeriod(val OptLeaderboardResponsePeriod) {
	s.Period = val
}

// SetSort sets the value of Sort.
func (s *LeaderboardResponse) SetSort(val OptLeaderboardResponseSort) {
	s.Sort = val
}

// SetGeneratedAt sets the value of GeneratedAt.
func (s *LeaderboardResponse) SetGeneratedAt(val OptInt64) {
	s.GeneratedAt = val
}

// SetPlayers sets the value of Players.
func (s *LeaderboardResponse) SetPlayers(val []LeaderboardEntry) {
	s.Players = val
}

func (*LeaderboardResponse) getLeaderboardRes() {}

// Leaderboard period.
type LeaderboardResponsePeriod string

const (
	LeaderboardResponsePeriodWeek  LeaderboardResponsePeriod = "week"
	LeaderboardResponsePeriodMonth LeaderboardResponsePeriod = "month"
)

// AllValues returns all LeaderboardResponsePeriod values.
func (LeaderboardResponsePeriod) AllValues() []LeaderboardResponsePeriod {
	return []LeaderboardResponsePeriod{
		LeaderboardResponsePeriodWeek,
		LeaderboardResponsePeriodMonth,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LeaderboardResponsePeriod) MarshalText() ([]byte, error) {
	switch s {
	case LeaderboardResponsePeriodWeek:
		return []byte(s), nil
	case LeaderboardResponsePeriodMonth:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LeaderboardResponsePeriod) UnmarshalText(data []byte) error {
	switch LeaderboardResponsePeriod(data) {
	case LeaderboardResponsePeriodWeek:
		*s = LeaderboardResponsePeriodWeek
		return nil
	case LeaderboardResponsePeriodMonth:
		*s = LeaderboardResponsePeriodMonth
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Sort field.
type LeaderboardResponseSort string

const (
	LeaderboardResponseSortRating LeaderboardResponseSort = "rating"
	LeaderboardResponseSortExp    LeaderboardResponseSort = "exp"
)

// AllValues returns all LeaderboardResponseSort values.
func (LeaderboardResponseSort) AllValues() []LeaderboardResponseSort {
	return []LeaderboardResponseSort{
		LeaderboardResponseSortRating,
		LeaderboardResponseSortExp,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LeaderboardResponseSort) MarshalText() ([]byte, error) {
	switch s {
	case LeaderboardResponseSortRating:
		return []byte(s), nil
	case LeaderboardResponseSortExp:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LeaderboardResponseSort) UnmarshalText(data []byte) error {
	switch LeaderboardResponseSort(data) {
	case LeaderboardResponseSortRating:
		*s = LeaderboardResponseSortRating
		return nil
	case LeaderboardResponseSortExp:
		*s = LeaderboardResponseSortExp
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ListGamesResponse
type ListGamesResponse struct {
	Games []GameSummary `json:"games"`
}

// GetGames returns the value of Games.
func (s *ListGamesResponse) GetGames() []GameSummary {
	return s.Games
}

// SetGames sets the value of Games.
func (s *ListGamesResponse) SetGames(val []GameSummary) {
	s.Games = val
}

func (*ListGamesResponse) listGamesRes() {}

// Ref: #/components/schemas/LobbyPlayer
type LobbyPlayer struct {
	// Player's ID.
	UID OptUUID `json:"uid"`
	// Player's total EXP.
	Exp OptInt64 `json:"exp"`
	// Player's ELO rating.
	Rating OptInt64 `json:"rating"`
}

// GetUID returns the value of UID.
func (s *LobbyPlayer) GetUID() OptUUID {
	return s.UID
}

// GetExp returns the value of Exp.
func (s *LobbyPlayer) GetExp() OptInt64 {
	return s.Exp
}

// GetRating returns the value of Rating.
func (s *LobbyPlayer) GetRating() OptInt64 {
	return s.Rating
}

// SetUID sets the value of UID.
func (s *LobbyPlayer) SetUID(val OptUUID) {
	s.UID = val
}

// SetExp sets the value of Exp.
func (s *LobbyPlayer) SetExp(val OptInt64) {
	s.Exp = val
}

// SetRating sets the value of Rating.
func (s *LobbyPlayer) SetRating(val OptInt64) {
	s.Rating = val
}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct{}

func (*LogoutNoContent) logoutRes() {}

// Ref: #/components/schemas/LogoutRequest
type LogoutRequest struct {
	// Optional. The refresh token to revoke for this device.
	RefreshToken OptString `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *LogoutRequest) GetRefreshToken() OptString {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *LogoutRequest) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

type MoveGameBadRequest ErrorResponse

func (*MoveGameBadRequest) moveGameRes() {}

type MoveGameConflict ErrorResponse

func (*MoveGameConflict) moveGameRes() {}

type MoveGameForbidden ErrorResponse

func (*MoveGameForbidden) moveGameRes() {}

type MoveGameInternalServerError ErrorResponse

func (*MoveGameInternalServerError) moveGameRes() {}

type MoveGameNotFound ErrorResponse

func (*MoveGameNotFound) moveGameRes() {}

type MoveGameUnauthorized ErrorResponse

func (*MoveGameUnauthorized) moveGameRes() {}

// Ref: #/components/schemas/MoveRequest
type MoveRequest struct {
	NewLetter MoveRequestNewLetter `json:"new_letter"`
	WordPath  []BoardCell          `json:"word_path"`
}

// GetNewLetter returns the value of NewLetter.
func (s *MoveRequest) GetNewLetter() MoveRequestNewLetter {
	return s.NewLetter
}

// GetWordPath returns the value of WordPath.
func (s *MoveRequest) GetWordPath() []BoardCell {
	return s.WordPath
}

// SetNewLetter sets the value of NewLetter.
func (s *MoveRequest) SetNewLetter(val MoveRequestNewLetter) {
	s.NewLetter = val
}

// SetWordPath sets the value of WordPath.
func (s *MoveRequest) SetWordPath(val []BoardCell) {
	s.WordPath = val
}

type MoveRequestNewLetter struct {
	Row int `json:"row"`
	Col int `json:"col"`
	// Single Cyrillic letter to place.
	Char string `json:"char"`
}

// GetRow returns the value of Row.
func (s *MoveRequestNewLetter) GetRow() int {
	return s.Row
}

// GetCol returns the value of Col.
func (s *MoveRequestNewLetter) GetCol() int {
	return s.Col
}

// GetChar returns the value of Char.
func (s *MoveRequestNewLetter) GetChar() string {
	return s.Char
}

// SetRow sets the value of Row.
func (s *MoveRequestNewLetter) SetRow(val int) {
	s.Row = val
}

// SetCol sets the value of Col.
func (s *MoveRequestNewLetter) SetCol(val int) {
	s.Col = val
}

// SetChar sets the value of Char.
func (s *MoveRequestNewLetter) SetChar(val string) {
	s.Char = val
}

// Ref: #/components/schemas/MoveResponse
type MoveResponse struct {
	// Updated 5x5 board state.
	Board [][]string `json:"board"`
	// ID of the player whose turn it is now.
	CurrentTurnUID OptUUID           `json:"current_turn_uid"`
	Players        []PlayerGameState `json:"players"`
	Status         OptGameStatus     `json:"status"`
	MoveNumber     OptInt            `json:"move_number"`
}

// GetBoard returns the value of Board.
func (s *MoveResponse) GetBoard() [][]string {
	return s.Board
}

// GetCurrentTurnUID returns the value of CurrentTurnUID.
func (s *MoveResponse) GetCurrentTurnUID() OptUUID {
	return s.CurrentTurnUID
}

// GetPlayers returns the value of Players.
func (s *MoveResponse) GetPlayers() []PlayerGameState {
	return s.Players
}

// GetStatus returns the value of Status.
func (s *MoveResponse) GetStatus() OptGameStatus {
	return s.Status
}

// GetMoveNumber returns the value of MoveNumber.
func (s *MoveResponse) GetMoveNumber() OptInt {
	return s.MoveNumber
}

// SetBoard sets the value of Board.
func (s *MoveResponse) SetBoard(val [][]string) {
	s.Board = val
}

// SetCurrentTurnUID sets the value of CurrentTurnUID.
func (s *MoveResponse) SetCurrentTurnUID(val OptUUID) {
	s.CurrentTurnUID = val
}

// SetPlayers sets the value of Players.
func (s *MoveResponse) SetPlayers(val []PlayerGameState) {
	s.Players = val
}

// SetStatus sets the value of Status.
func (s *MoveResponse) SetStatus(val OptGameStatus) {
	s.Status = val
}

// SetMoveNumber sets the value of MoveNumber.
func (s *MoveResponse) SetMoveNumber(val OptInt) {
	s.MoveNumber = val
}

func (*MoveResponse) moveGameRes() {}

// NewOptAchievementID returns new OptAchievementID with value set to v.
func NewOptAchievementID(v AchievementID) OptAchievementID {
	return OptAchievementID{
		Value: v,
		Set:   true,
	}
}

// OptAchievementID is optional AchievementID.
type OptAchievementID struct {
	Value AchievementID
	Set   bool
}

// IsSet returns true if OptAchievementID was set.
func (o OptAchievementID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAchievementID) Reset() {
	var v AchievementID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAchievementID) SetTo(v AchievementID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAchievementID) Get() (v AchievementID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAchievementID) Or(d AchievementID) AchievementID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptActiveGame returns new OptActiveGame with value set to v.
func NewOptActiveGame(v ActiveGame) OptActiveGame {
	return OptActiveGame{
		Value: v,
		Set:   true,
	}
}

// OptActiveGame is optional ActiveGame.
type OptActiveGame struct {
	Value ActiveGame
	Set   bool
}

// IsSet returns true if OptActiveGame was set.
func (o OptActiveGame) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptActiveGame) Reset() {
	var v ActiveGame
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptActiveGame) SetTo(v ActiveGame) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptActiveGame) Get() (v ActiveGame, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptActiveGame) Or(d ActiveGame) ActiveGame {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGameStatus returns new OptGameStatus with value set to v.
func NewOptGameStatus(v GameStatus) OptGameStatus {
	return OptGameStatus{
		Value: v,
		Set:   true,
	}
}

// OptGameStatus is optional GameStatus.
type OptGameStatus struct {
	Value GameStatus
	Set   bool
}

// IsSet returns true if OptGameStatus was set.
func (o OptGameStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGameStatus) Reset() {
	var v GameStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGameStatus) SetTo(v GameStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGameStatus) Get() (v GameStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGameStatus) Or(d GameStatus) GameStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGameSummary returns new OptGameSummary with value set to v.
func NewOptGameSummary(v GameSummary) OptGameSummary {
	return OptGameSummary{
		Value: v,
		Set:   true,
	}
}

// OptGameSummary is optional GameSummary.
type OptGameSummary struct {
	Value GameSummary
	Set   bool
}

// IsSet returns true if OptGameSummary was set.
func (o OptGameSummary) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGameSummary) Reset() {
	var v GameSummary
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGameSummary) SetTo(v GameSummary) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGameSummary) Get() (v GameSummary, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGameSummary) Or(d GameSummary) GameSummary {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGetLeaderboardSort returns new OptGetLeaderboardSort with value set to v.
func NewOptGetLeaderboardSort(v GetLeaderboardSort) OptGetLeaderboardSort {
	return OptGetLeaderboardSort{
		Value: v,
		Set:   true,
	}
}

// OptGetLeaderboardSort is optional GetLeaderboardSort.
type OptGetLeaderboardSort struct {
	Value GetLeaderboardSort
	Set   bool
}

// IsSet returns true if OptGetLeaderboardSort was set.
func (o OptGetLeaderboardSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetLeaderboardSort) Reset() {
	var v GetLeaderboardSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetLeaderboardSort) SetTo(v GetLeaderboardSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetLeaderboardSort) Get() (v GetLeaderboardSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetLeaderboardSort) Or(d GetLeaderboardSort) GetLeaderboardSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLeaderboardResponsePeriod returns new OptLeaderboardResponsePeriod with value set to v.
func NewOptLeaderboardResponsePeriod(v LeaderboardResponsePeriod) OptLeaderboardResponsePeriod {
	return OptLeaderboardResponsePeriod{
		Value: v,
		Set:   true,
	}
}

// OptLeaderboardResponsePeriod is optional LeaderboardResponsePeriod.
type OptLeaderboardResponsePeriod struct {
	Value LeaderboardResponsePeriod
	Set   bool
}

// IsSet returns true if OptLeaderboardResponsePeriod was set.
func (o OptLeaderboardResponsePeriod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLeaderboardResponsePeriod) Reset() {
	var v LeaderboardResponsePeriod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLeaderboardResponsePeriod) SetTo(v LeaderboardResponsePeriod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLeaderboardResponsePeriod) Get() (v LeaderboardResponsePeriod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLeaderboardResponsePeriod) Or(d LeaderboardResponsePeriod) LeaderboardResponsePeriod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLeaderboardResponseSort returns new OptLeaderboardResponseSort with value set to v.
func NewOptLeaderboardResponseSort(v LeaderboardResponseSort) OptLeaderboardResponseSort {
	return OptLeaderboardResponseSort{
		Value: v,
		Set:   true,
	}
}

// OptLeaderboardResponseSort is optional LeaderboardResponseSort.
type OptLeaderboardResponseSort struct {
	Value LeaderboardResponseSort
	Set   bool
}

// IsSet returns true if OptLeaderboardResponseSort was set.
func (o OptLeaderboardResponseSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLeaderboardResponseSort) Reset() {
	var v LeaderboardResponseSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLeaderboardResponseSort) SetTo(v LeaderboardResponseSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLeaderboardResponseSort) Get() (v LeaderboardResponseSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLeaderboardResponseSort) Or(d LeaderboardResponseSort) LeaderboardResponseSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLogoutRequest returns new OptLogoutRequest with value set to v.
func NewOptLogoutRequest(v LogoutRequest) OptLogoutRequest {
	return OptLogoutRequest{
		Value: v,
		Set:   true,
	}
}

// OptLogoutRequest is optional LogoutRequest.
type OptLogoutRequest struct {
	Value LogoutRequest
	Set   bool
}

// IsSet returns true if OptLogoutRequest was set.
func (o OptLogoutRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLogoutRequest) Reset() {
	var v LogoutRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLogoutRequest) SetTo(v LogoutRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLogoutRequest) Get() (v LogoutRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLogoutRequest) Or(d LogoutRequest) LogoutRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPlayer returns new OptPlayer with value set to v.
func NewOptPlayer(v Player) OptPlayer {
	return OptPlayer{
		Value: v,
		Set:   true,
	}
}

// OptPlayer is optional Player.
type OptPlayer struct {
	Value Player
	Set   bool
}

// IsSet returns true if OptPlayer was set.
func (o OptPlayer) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPlayer) Reset() {
	var v Player
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPlayer) SetTo(v Player) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPlayer) Get() (v Player, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPlayer) Or(d Player) Player {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PingNoContent is response for Ping operation.
type PingNoContent struct {
	XRequestID  OptInt64
	XServerTime OptInt64
}

// GetXRequestID returns the value of XRequestID.
func (s *PingNoContent) GetXRequestID() OptInt64 {
	return s.XRequestID
}

// GetXServerTime returns the value of XServerTime.
func (s *PingNoContent) GetXServerTime() OptInt64 {
	return s.XServerTime
}

// SetXRequestID sets the value of XRequestID.
func (s *PingNoContent) SetXRequestID(val OptInt64) {
	s.XRequestID = val
}

// SetXServerTime sets the value of XServerTime.
func (s *PingNoContent) SetXServerTime(val OptInt64) {
	s.XServerTime = val
}

func (*PingNoContent) pingRes() {}

// Ref: #/components/schemas/Player
type Player struct {
	// Player's ID in the system.
	UID OptUUID `json:"uid"`
	// Player's first name.
	Firstname OptString `json:"firstname"`
	// Player's last name.
	Lastname OptString `json:"lastname"`
	// Player's total EXP.
	Exp OptInt64 `json:"exp"`
	// Player's ELO rating.
	Rating OptInt64 `json:"rating"`
}

// GetUID returns the value of UID.
func (s *Player) GetUID() OptUUID {
	return s.UID
}

// GetFirstname returns the value of Firstname.
func (s *Player) GetFirstname() OptString {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *Player) GetLastname() OptString {
	return s.Lastname
}

// GetExp returns the value of Exp.
func (s *Player) GetExp() OptInt64 {
	return s.Exp
}

// GetRating returns the value of Rating.
func (s *Player) GetRating() OptInt64 {
	return s.Rating
}

// SetUID sets the value of UID.
func (s *Player) SetUID(val OptUUID) {
	s.UID = val
}

// SetFirstname sets the value of Firstname.
func (s *Player) SetFirstname(val OptString) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *Player) SetLastname(val OptString) {
	s.Lastname = val
}

// SetExp sets the value of Exp.
func (s *Player) SetExp(val OptInt64) {
	s.Exp = val
}

// SetRating sets the value of Rating.
func (s *Player) SetRating(val OptInt64) {
	s.Rating = val
}

// Ref: #/components/schemas/PlayerAchievementsResponse
type PlayerAchievementsResponse struct {
	// Full list of achievements with unlocked status.
	Achievements []Achievement `json:"achievements"`
}

// GetAchievements returns the value of Achievements.
func (s *PlayerAchievementsResponse) GetAchievements() []Achievement {
	return s.Achievements
}

// SetAchievements sets the value of Achievements.
func (s *PlayerAchievementsResponse) SetAchievements(val []Achievement) {
	s.Achievements = val
}

func (*PlayerAchievementsResponse) getPlayerAchievementsRes() {}

// Ref: #/components/schemas/PlayerGameState
type PlayerGameState struct {
	// Player's ID.
	UID OptUUID `json:"uid"`
	// Player's total EXP at the time of the event.
	Exp OptInt64 `json:"exp"`
	// Player's ELO rating at the time of the event.
	Rating OptInt64 `json:"rating"`
	// EXP earned in this game (only present in game_over events).
	ExpGained OptInt `json:"exp_gained"`
	// Number of points scored in the current game.
	Score OptInt `json:"score"`
	// Number of words submitted by the player.
	WordsCount OptInt `json:"words_count"`
	// List of words submitted by the player in this game.
	Words []string `json:"words"`
}

// GetUID returns the value of UID.
func (s *PlayerGameState) GetUID() OptUUID {
	return s.UID
}

// GetExp returns the value of Exp.
func (s *PlayerGameState) GetExp() OptInt64 {
	return s.Exp
}

// GetRating returns the value of Rating.
func (s *PlayerGameState) GetRating() OptInt64 {
	return s.Rating
}

// GetExpGained returns the value of ExpGained.
func (s *PlayerGameState) GetExpGained() OptInt {
	return s.ExpGained
}

// GetScore returns the value of Score.
func (s *PlayerGameState) GetScore() OptInt {
	return s.Score
}

// GetWordsCount returns the value of WordsCount.
func (s *PlayerGameState) GetWordsCount() OptInt {
	return s.WordsCount
}

// GetWords returns the value of Words.
func (s *PlayerGameState) GetWords() []string {
	return s.Words
}

// SetUID sets the value of UID.
func (s *PlayerGameState) SetUID(val OptUUID) {
	s.UID = val
}

// SetExp sets the value of Exp.
func (s *PlayerGameState) SetExp(val OptInt64) {
	s.Exp = val
}

// SetRating sets the value of Rating.
func (s *PlayerGameState) SetRating(val OptInt64) {
	s.Rating = val
}

// SetExpGained sets the value of ExpGained.
func (s *PlayerGameState) SetExpGained(val OptInt) {
	s.ExpGained = val
}

// SetScore sets the value of Score.
func (s *PlayerGameState) SetScore(val OptInt) {
	s.Score = val
}

// SetWordsCount sets the value of WordsCount.
func (s *PlayerGameState) SetWordsCount(val OptInt) {
	s.WordsCount = val
}

// SetWords sets the value of Words.
func (s *PlayerGameState) SetWords(val []string) {
	s.Words = val
}

// Ref: #/components/schemas/PlayerState
type PlayerState struct {
	// Player's ID in the system.
	UID OptUUID `json:"uid"`
	// Generated nickname in the system.
	Nickname OptString `json:"nickname"`
	// Player's exp points in the system.
	Exp OptInt64 `json:"exp"`
	// Player's ELO rating in the system.
	Rating OptInt64 `json:"rating"`
	// Player's lives count in the system.
	Lives OptInt64 `json:"lives"`
	// Some Player's flags.
	Flags OptInt64 `json:"flags"`
	// Game's ID (if game_id empty or absent then player in the lobby).
	GameID OptUUID `json:"game_id"`
}

// GetUID returns the value of UID.
func (s *PlayerState) GetUID() OptUUID {
	return s.UID
}

// GetNickname returns the value of Nickname.
func (s *PlayerState) GetNickname() OptString {
	return s.Nickname
}

// GetExp returns the value of Exp.
func (s *PlayerState) GetExp() OptInt64 {
	return s.Exp
}

// GetRating returns the value of Rating.
func (s *PlayerState) GetRating() OptInt64 {
	return s.Rating
}

// GetLives returns the value of Lives.
func (s *PlayerState) GetLives() OptInt64 {
	return s.Lives
}

// GetFlags returns the value of Flags.
func (s *PlayerState) GetFlags() OptInt64 {
	return s.Flags
}

// GetGameID returns the value of GameID.
func (s *PlayerState) GetGameID() OptUUID {
	return s.GameID
}

// SetUID sets the value of UID.
func (s *PlayerState) SetUID(val OptUUID) {
	s.UID = val
}

// SetNickname sets the value of Nickname.
func (s *PlayerState) SetNickname(val OptString) {
	s.Nickname = val
}

// SetExp sets the value of Exp.
func (s *PlayerState) SetExp(val OptInt64) {
	s.Exp = val
}

// SetRating sets the value of Rating.
func (s *PlayerState) SetRating(val OptInt64) {
	s.Rating = val
}

// SetLives sets the value of Lives.
func (s *PlayerState) SetLives(val OptInt64) {
	s.Lives = val
}

// SetFlags sets the value of Flags.
func (s *PlayerState) SetFlags(val OptInt64) {
	s.Flags = val
}

// SetGameID sets the value of GameID.
func (s *PlayerState) SetGameID(val OptUUID) {
	s.GameID = val
}

func (*PlayerState) getPlayerStateUIDRes() {}

// Ref: #/components/schemas/PlayerStatsResponse
type PlayerStatsResponse struct {
	// Total number of finished games.
	GamesPlayed OptInt64 `json:"games_played"`
	// Number of games won.
	Wins OptInt64 `json:"wins"`
	// Number of games lost.
	Losses OptInt64 `json:"losses"`
	// Number of games ended in a draw.
	Draws OptInt64 `json:"draws"`
	// Win rate as a fraction (0..1).
	WinRate OptFloat64 `json:"win_rate"`
	// Average length of submitted words in letters.
	AvgWordLength OptFloat64 `json:"avg_word_length"`
	// Longest word ever submitted (empty if no games with recorded words).
	BestWord OptString `json:"best_word"`
	// Most frequently used letter across all submitted words (empty if none).
	FavoriteLetter OptString `json:"favorite_letter"`
}

// GetGamesPlayed returns the value of GamesPlayed.
func (s *PlayerStatsResponse) GetGamesPlayed() OptInt64 {
	return s.GamesPlayed
}

// GetWins returns the value of Wins.
func (s *PlayerStatsResponse) GetWins() OptInt64 {
	return s.Wins
}

// GetLosses returns the value of Losses.
func (s *PlayerStatsResponse) GetLosses() OptInt64 {
	return s.Losses
}

// GetDraws returns the value of Draws.
func (s *PlayerStatsResponse) GetDraws() OptInt64 {
	return s.Draws
}

// GetWinRate returns the value of WinRate.
func (s *PlayerStatsResponse) GetWinRate() OptFloat64 {
	return s.WinRate
}

// GetAvgWordLength returns the value of AvgWordLength.
func (s *PlayerStatsResponse) GetAvgWordLength() OptFloat64 {
	return s.AvgWordLength
}

// GetBestWord returns the value of BestWord.
func (s *PlayerStatsResponse) GetBestWord() OptString {
	return s.BestWord
}

// GetFavoriteLetter returns the value of FavoriteLetter.
func (s *PlayerStatsResponse) GetFavoriteLetter() OptString {
	return s.FavoriteLetter
}

// SetGamesPlayed sets the value of GamesPlayed.
func (s *PlayerStatsResponse) SetGamesPlayed(val OptInt64) {
	s.GamesPlayed = val
}

// SetWins sets the value of Wins.
func (s *PlayerStatsResponse) SetWins(val OptInt64) {
	s.Wins = val
}

// SetLosses sets the value of Losses.
func (s *PlayerStatsResponse) SetLosses(val OptInt64) {
	s.Losses = val
}

// SetDraws sets the value of Draws.
func (s *PlayerStatsResponse) SetDraws(val OptInt64) {
	s.Draws = val
}

// SetWinRate sets the value of WinRate.
func (s *PlayerStatsResponse) SetWinRate(val OptFloat64) {
	s.WinRate = val
}

// SetAvgWordLength sets the value of AvgWordLength.
func (s *PlayerStatsResponse) SetAvgWordLength(val OptFloat64) {
	s.AvgWordLength = val
}

// SetBestWord sets the value of BestWord.
func (s *PlayerStatsResponse) SetBestWord(val OptString) {
	s.BestWord = val
}

// SetFavoriteLetter sets the value of FavoriteLetter.
func (s *PlayerStatsResponse) SetFavoriteLetter(val OptString) {
	s.FavoriteLetter = val
}

func (*PlayerStatsResponse) getPlayerStatsRes() {}

type ProposeEndGameConflict ErrorResponse

func (*ProposeEndGameConflict) proposeEndGameRes() {}

type ProposeEndGameForbidden ErrorResponse

func (*ProposeEndGameForbidden) proposeEndGameRes() {}

// ProposeEndGameNoContent is response for ProposeEndGame operation.
type ProposeEndGameNoContent struct{}

func (*ProposeEndGameNoContent) proposeEndGameRes() {}

type ProposeEndGameNotFound ErrorResponse

func (*ProposeEndGameNotFound) proposeEndGameRes() {}

type ProposeEndGameUnauthorized ErrorResponse

func (*ProposeEndGameUnauthorized) proposeEndGameRes() {}

// Ref: #/components/schemas/RefreshRequest
type RefreshRequest struct {
	// The opaque refresh token previously issued.
	RefreshToken string `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshRequest) GetRefreshToken() string {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshRequest) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/RefreshResponse
type RefreshResponse struct {
	// New short-lived JWT access token.
	AccessToken OptString `json:"access_token"`
	// New opaque refresh token (rotated; the old one is now invalid).
	RefreshToken OptString `json:"refresh_token"`
	// Always "Bearer".
	TokenType OptString `json:"token_type"`
	// Access token lifetime in seconds.
	ExpiresIn OptInt `json:"expires_in"`
}

// GetAccessToken returns the value of AccessToken.
func (s *RefreshResponse) GetAccessToken() OptString {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshResponse) GetRefreshToken() OptString {
	return s.RefreshToken
}

// GetTokenType returns the value of TokenType.
func (s *RefreshResponse) GetTokenType() OptString {
	return s.TokenType
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *RefreshResponse) GetExpiresIn() OptInt {
	return s.ExpiresIn
}

// SetAccessToken sets the value of AccessToken.
func (s *RefreshResponse) SetAccessToken(val OptString) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshResponse) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

// SetTokenType sets the value of TokenType.
func (s *RefreshResponse) SetTokenType(val OptString) {
	s.TokenType = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *RefreshResponse) SetExpiresIn(val OptInt) {
	s.ExpiresIn = val
}

func (*RefreshResponse) refreshTokenRes() {}

type RejectEndGameConflict ErrorResponse

func (*RejectEndGameConflict) rejectEndGameRes() {}

type RejectEndGameForbidden ErrorResponse

func (*RejectEndGameForbidden) rejectEndGameRes() {}

// RejectEndGameNoContent is response for RejectEndGame operation.
type RejectEndGameNoContent struct{}

func (*RejectEndGameNoContent) rejectEndGameRes() {}

type RejectEndGameNotFound ErrorResponse

func (*RejectEndGameNotFound) rejectEndGameRes() {}

type RejectEndGameUnauthorized ErrorResponse

func (*RejectEndGameUnauthorized) rejectEndGameRes() {}

// Ref: #/components/schemas/SignupRequest
type SignupRequest struct {
	// User's first name.
	Firstname string `json:"firstname"`
	// User's last name.
	Lastname string `json:"lastname"`
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetFirstname returns the value of Firstname.
func (s *SignupRequest) GetFirstname() string {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *SignupRequest) GetLastname() string {
	return s.Lastname
}

// GetEmail returns the value of Email.
func (s *SignupRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignupRequest) GetPassword() string {
	return s.Password
}

// SetFirstname sets the value of Firstname.
func (s *SignupRequest) SetFirstname(val string) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *SignupRequest) SetLastname(val string) {
	s.Lastname = val
}

// SetEmail sets the value of Email.
func (s *SignupRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignupRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/SignupResponse
type SignupResponse struct {
	User OptPlayer `json:"user"`
	// Short-lived JWT access token (Authorization:&nbsp;Bearer).
	AccessToken OptString `json:"access_token"`
	// Opaque long-lived token used to obtain a new access token.
	RefreshToken OptString `json:"refresh_token"`
	// Always "Bearer".
	TokenType OptString `json:"token_type"`
	// Access token lifetime in seconds.
	ExpiresIn OptInt `json:"expires_in"`
	// JWT for connecting to the Centrifugo WebSocket.
	CentrifugoToken OptString `json:"centrifugo_token"`
	// Centrifugo subscription JWT for the lobby channel.
	LobbyToken OptString `json:"lobby_token"`
}

// GetUser returns the value of User.
func (s *SignupResponse) GetUser() OptPlayer {
	return s.User
}

// GetAccessToken returns the value of AccessToken.
func (s *SignupResponse) GetAccessToken() OptString {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *SignupResponse) GetRefreshToken() OptString {
	return s.RefreshToken
}

// GetTokenType returns the value of TokenType.
func (s *SignupResponse) GetTokenType() OptString {
	return s.TokenType
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *SignupResponse) GetExpiresIn() OptInt {
	return s.ExpiresIn
}

// GetCentrifugoToken returns the value of CentrifugoToken.
func (s *SignupResponse) GetCentrifugoToken() OptString {
	return s.CentrifugoToken
}

// GetLobbyToken returns the value of LobbyToken.
func (s *SignupResponse) GetLobbyToken() OptString {
	return s.LobbyToken
}

// SetUser sets the value of User.
func (s *SignupResponse) SetUser(val OptPlayer) {
	s.User = val
}

// SetAccessToken sets the value of AccessToken.
func (s *SignupResponse) SetAccessToken(val OptString) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *SignupResponse) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

// SetTokenType sets the value of TokenType.
func (s *SignupResponse) SetTokenType(val OptString) {
	s.TokenType = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *SignupResponse) SetExpiresIn(val OptInt) {
	s.ExpiresIn = val
}

// SetCentrifugoToken sets the value of CentrifugoToken.
func (s *SignupResponse) SetCentrifugoToken(val OptString) {
	s.CentrifugoToken = val
}

// SetLobbyToken sets the value of LobbyToken.
func (s *SignupResponse) SetLobbyToken(val OptString) {
	s.LobbyToken = val
}

func (*SignupResponse) signupRes() {}

type SkipGameConflict ErrorResponse

func (*SkipGameConflict) skipGameRes() {}

type SkipGameForbidden ErrorResponse

func (*SkipGameForbidden) skipGameRes() {}

// SkipGameNoContent is response for SkipGame operation.
type SkipGameNoContent struct{}

func (*SkipGameNoContent) skipGameRes() {}

type SkipGameNotFound ErrorResponse

func (*SkipGameNotFound) skipGameRes() {}

type SkipGameUnauthorized ErrorResponse

func (*SkipGameUnauthorized) skipGameRes() {}

// Ref: #/components/schemas/TelegramAuthRequest
type TelegramAuthRequest struct {
	// Raw init data string provided by the Telegram WebView (window.Telegram.WebApp.initData).
	InitData string `json:"init_data"`
}

// GetInitData returns the value of InitData.
func (s *TelegramAuthRequest) GetInitData() string {
	return s.InitData
}

// SetInitData sets the value of InitData.
func (s *TelegramAuthRequest) SetInitData(val string) {
	s.InitData = val
}
