// Code generated by ogen, DO NOT EDIT.

package baldaapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AcceptEndGameOperation     OperationName = "AcceptEndGame"
	AuthOperation              OperationName = "Auth"
	CreateGameOperation        OperationName = "CreateGame"
	GetPlayerStateUIDOperation OperationName = "GetPlayerStateUID"
	JoinGameOperation          OperationName = "JoinGame"
	ListGamesOperation         OperationName = "ListGames"
	MoveGameOperation          OperationName = "MoveGame"
	PingOperation              OperationName = "Ping"
	ProposeEndGameOperation    OperationName = "ProposeEndGame"
	RejectEndGameOperation     OperationName = "RejectEndGame"
	SignupOperation            OperationName = "Signup"
	SkipGameOperation          OperationName = "SkipGame"
)
