// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Auth implements auth operation.
//
// Auth request.
//
// POST /auth
func (UnimplementedHandler) Auth(ctx context.Context, req *AuthRequest) (r AuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGame implements createGame operation.
//
// Create a new game.
//
// POST /games
func (UnimplementedHandler) CreateGame(ctx context.Context, params CreateGameParams) (r CreateGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerStateUID implements getPlayerStateUID operation.
//
// Get user state.
//
// GET /player/state/{uid}
func (UnimplementedHandler) GetPlayerStateUID(ctx context.Context, params GetPlayerStateUIDParams) (r GetPlayerStateUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// JoinGame implements joinGame operation.
//
// Adds the authenticated player to the specified waiting game.
// When the second player joins (quorum of 2 is reached) the game
// transitions to in_progress and the first move belongs to the
// player who created the game.
//
// POST /games/{id}/join
func (UnimplementedHandler) JoinGame(ctx context.Context, params JoinGameParams) (r JoinGameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGames implements listGames operation.
//
// Returns a snapshot of all currently active games.
//
// GET /games
func (UnimplementedHandler) ListGames(ctx context.Context, params ListGamesParams) (r ListGamesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// POST not GET — mutates session TTL.
// Returns 204 with X-Server-Time header instead of a JSON body
// to minimize bandwidth on frequent pings (every ping_delay ms).
//
// POST /session/ping
func (UnimplementedHandler) Ping(ctx context.Context, params PingParams) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Signup implements signup operation.
//
// Sign-up request.
//
// POST /signup
func (UnimplementedHandler) Signup(ctx context.Context, req *SignupRequest) (r SignupRes, _ error) {
	return r, ht.ErrNotImplemented
}
