// Code generated by ogen, DO NOT EDIT.
package baldaapi

type AcceptEndGameRes interface {
	acceptEndGameRes()
}

type AuthRes interface {
	authRes()
}

type CreateGameRes interface {
	createGameRes()
}

type CreateGameWithBotRes interface {
	createGameWithBotRes()
}

type GetLeaderboardRes interface {
	getLeaderboardRes()
}

type GetPlayerAchievementsRes interface {
	getPlayerAchievementsRes()
}

type GetPlayerStateUIDRes interface {
	getPlayerStateUIDRes()
}

type JoinGameRes interface {
	joinGameRes()
}

type ListGamesRes interface {
	listGamesRes()
}

type LogoutRes interface {
	logoutRes()
}

type MoveGameRes interface {
	moveGameRes()
}

type PingRes interface {
	pingRes()
}

type ProposeEndGameRes interface {
	proposeEndGameRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type RejectEndGameRes interface {
	rejectEndGameRes()
}

type SignupRes interface {
	signupRes()
}

type SkipGameRes interface {
	skipGameRes()
}
