// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Auth implements auth operation.
//
// Auth request.
//
// POST /auth
func (UnimplementedHandler) Auth(ctx context.Context, req *AuthRequest) (r AuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerStateUID implements getPlayerStateUID operation.
//
// Get user state.
//
// GET /player/state/{uid}
func (UnimplementedHandler) GetPlayerStateUID(ctx context.Context, params GetPlayerStateUIDParams) (r GetPlayerStateUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Signup implements signup operation.
//
// Sign-up request.
//
// POST /signup
func (UnimplementedHandler) Signup(ctx context.Context, req *SignupRequest) (r SignupRes, _ error) {
	return r, ht.ErrNotImplemented
}
