// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AcceptEndGameParams is parameters of acceptEndGame operation.
type AcceptEndGameParams struct {
	XAPISession string
	// ID of the game.
	ID uuid.UUID
}

func unpackAcceptEndGameParams(packed middleware.Parameters) (params AcceptEndGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAcceptEndGameParams(args [1]string, argsEscaped bool, r *http.Request) (params AcceptEndGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateGameParams is parameters of createGame operation.
type CreateGameParams struct {
	XAPISession string
}

func unpackCreateGameParams(packed middleware.Parameters) (params CreateGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	return params
}

func decodeCreateGameParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// GetPlayerStateUIDParams is parameters of getPlayerStateUID operation.
type GetPlayerStateUIDParams struct {
	// Player ID.
	UID uuid.UUID
}

func unpackGetPlayerStateUIDParams(packed middleware.Parameters) (params GetPlayerStateUIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "uid",
			In:   "path",
		}
		params.UID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPlayerStateUIDParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPlayerStateUIDParams, _ error) {
	// Decode path: uid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "uid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "uid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// JoinGameParams is parameters of joinGame operation.
type JoinGameParams struct {
	XAPISession string
	// ID of the game to join.
	ID uuid.UUID
}

func unpackJoinGameParams(packed middleware.Parameters) (params JoinGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeJoinGameParams(args [1]string, argsEscaped bool, r *http.Request) (params JoinGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListGamesParams is parameters of listGames operation.
type ListGamesParams struct {
	XAPISession string
}

func unpackListGamesParams(packed middleware.Parameters) (params ListGamesParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	return params
}

func decodeListGamesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListGamesParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// MoveGameParams is parameters of moveGame operation.
type MoveGameParams struct {
	XAPISession string
	// ID of the game.
	ID uuid.UUID
}

func unpackMoveGameParams(packed middleware.Parameters) (params MoveGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeMoveGameParams(args [1]string, argsEscaped bool, r *http.Request) (params MoveGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PingParams is parameters of ping operation.
type PingParams struct {
	XRequestID  int64
	XAPISession string
}

func unpackPingParams(packed middleware.Parameters) (params PingParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Request-ID",
			In:   "header",
		}
		params.XRequestID = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	return params
}

func decodePingParams(args [0]string, argsEscaped bool, r *http.Request) (params PingParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Request-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Request-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.XRequestID = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.XRequestID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Request-ID",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// ProposeEndGameParams is parameters of proposeEndGame operation.
type ProposeEndGameParams struct {
	XAPISession string
	// ID of the game.
	ID uuid.UUID
}

func unpackProposeEndGameParams(packed middleware.Parameters) (params ProposeEndGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeProposeEndGameParams(args [1]string, argsEscaped bool, r *http.Request) (params ProposeEndGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RejectEndGameParams is parameters of rejectEndGame operation.
type RejectEndGameParams struct {
	XAPISession string
	// ID of the game.
	ID uuid.UUID
}

func unpackRejectEndGameParams(packed middleware.Parameters) (params RejectEndGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeRejectEndGameParams(args [1]string, argsEscaped bool, r *http.Request) (params RejectEndGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SkipGameParams is parameters of skipGame operation.
type SkipGameParams struct {
	XAPISession string
	// ID of the game.
	ID uuid.UUID
}

func unpackSkipGameParams(packed middleware.Parameters) (params SkipGameParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-API-Session",
			In:   "header",
		}
		params.XAPISession = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSkipGameParams(args [1]string, argsEscaped bool, r *http.Request) (params SkipGameParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-API-Session.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-API-Session",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XAPISession = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-API-Session",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
