// Code generated by ogen, DO NOT EDIT.
package baldaapi

type AuthRes interface {
	authRes()
}

type GetPlayerStateUIDRes interface {
	getPlayerStateUIDRes()
}

type PingRes interface {
	pingRes()
}

type SignupRes interface {
	signupRes()
}
