// Code generated by ogen, DO NOT EDIT.

package baldaapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthOperation              OperationName = "Auth"
	GetPlayerStateUIDOperation OperationName = "GetPlayerStateUID"
	ListGamesOperation         OperationName = "ListGames"
	PingOperation              OperationName = "Ping"
	SignupOperation            OperationName = "Signup"
)
