// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Auth implements auth operation.
	//
	// Auth request.
	//
	// POST /auth
	Auth(ctx context.Context, req *AuthRequest) (AuthRes, error)
	// GetPlayerStateUID implements getPlayerStateUID operation.
	//
	// Get user state.
	//
	// GET /player/state/{uid}
	GetPlayerStateUID(ctx context.Context, params GetPlayerStateUIDParams) (GetPlayerStateUIDRes, error)
	// ListGames implements listGames operation.
	//
	// Returns a snapshot of all currently active games.
	//
	// GET /games
	ListGames(ctx context.Context, params ListGamesParams) (ListGamesRes, error)
	// Ping implements ping operation.
	//
	// POST not GET — mutates session TTL.
	// Returns 204 with X-Server-Time header instead of a JSON body
	// to minimize bandwidth on frequent pings (every ping_delay ms).
	//
	// POST /session/ping
	Ping(ctx context.Context, params PingParams) (PingRes, error)
	// Signup implements signup operation.
	//
	// Sign-up request.
	//
	// POST /signup
	Signup(ctx context.Context, req *SignupRequest) (SignupRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
