// Code generated by ogen, DO NOT EDIT.

package baldaapi

type APIKeyHeader struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyHeader) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyHeader) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyHeader) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyHeader) SetRoles(val []string) {
	s.Roles = val
}

type APIKeyQueryParam struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyQueryParam) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyQueryParam) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyQueryParam) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyQueryParam) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/AuthRequest
type AuthRequest struct {
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *AuthRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *AuthRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *AuthRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *AuthRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	User OptUser `json:"user"`
}

// GetUser returns the value of User.
func (s *AuthResponse) GetUser() OptUser {
	return s.User
}

// SetUser sets the value of User.
func (s *AuthResponse) SetUser(val OptUser) {
	s.User = val
}

func (*AuthResponse) authRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// The HTTP response code.
	Status OptInt `json:"status"`
	// A human-readable explanation of the error.
	Message OptString `json:"message"`
	// Type of the error message.
	Type OptString `json:"type"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() OptInt {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() OptString {
	return s.Message
}

// GetType returns the value of Type.
func (s *ErrorResponse) GetType() OptString {
	return s.Type
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val OptInt) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetType sets the value of Type.
func (s *ErrorResponse) SetType(val OptString) {
	s.Type = val
}

func (*ErrorResponse) authRes()             {}
func (*ErrorResponse) getUsersStateUIDRes() {}
func (*ErrorResponse) signupRes()           {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/SignupRequest
type SignupRequest struct {
	// User's first name.
	Firstname string `json:"firstname"`
	// User's last name.
	Lastname string `json:"lastname"`
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetFirstname returns the value of Firstname.
func (s *SignupRequest) GetFirstname() string {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *SignupRequest) GetLastname() string {
	return s.Lastname
}

// GetEmail returns the value of Email.
func (s *SignupRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignupRequest) GetPassword() string {
	return s.Password
}

// SetFirstname sets the value of Firstname.
func (s *SignupRequest) SetFirstname(val string) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *SignupRequest) SetLastname(val string) {
	s.Lastname = val
}

// SetEmail sets the value of Email.
func (s *SignupRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignupRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/SignupResponse
type SignupResponse struct {
	User OptUser `json:"user"`
}

// GetUser returns the value of User.
func (s *SignupResponse) GetUser() OptUser {
	return s.User
}

// SetUser sets the value of User.
func (s *SignupResponse) SetUser(val OptUser) {
	s.User = val
}

func (*SignupResponse) signupRes() {}

// Ref: #/components/schemas/User
type User struct {
	// User's ID in the system.
	UID OptInt64 `json:"uid"`
	// User's first name.
	Firstname OptString `json:"firstname"`
	// User's last name.
	Lastname OptString `json:"lastname"`
	// User's session ID.
	Sid OptString `json:"sid"`
	// User's API Key that the client needs to provide when making API calls.
	Key OptString `json:"key"`
}

// GetUID returns the value of UID.
func (s *User) GetUID() OptInt64 {
	return s.UID
}

// GetFirstname returns the value of Firstname.
func (s *User) GetFirstname() OptString {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *User) GetLastname() OptString {
	return s.Lastname
}

// GetSid returns the value of Sid.
func (s *User) GetSid() OptString {
	return s.Sid
}

// GetKey returns the value of Key.
func (s *User) GetKey() OptString {
	return s.Key
}

// SetUID sets the value of UID.
func (s *User) SetUID(val OptInt64) {
	s.UID = val
}

// SetFirstname sets the value of Firstname.
func (s *User) SetFirstname(val OptString) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *User) SetLastname(val OptString) {
	s.Lastname = val
}

// SetSid sets the value of Sid.
func (s *User) SetSid(val OptString) {
	s.Sid = val
}

// SetKey sets the value of Key.
func (s *User) SetKey(val OptString) {
	s.Key = val
}

// Ref: #/components/schemas/UserState
type UserState struct {
	// User's ID in the system.
	UID OptInt64 `json:"uid"`
	// Generated nickname in the system.
	Nickname OptString `json:"nickname"`
	// User's exp points in the system.
	Exp OptInt64 `json:"exp"`
	// User's lives count in the system.
	Lives OptInt64 `json:"lives"`
	// Game's ID (if game_id == 0 or absent then user in the lobby).
	GameID OptInt32 `json:"game_id"`
	// Some User's flags.
	Flags OptInt64 `json:"flags"`
}

// GetUID returns the value of UID.
func (s *UserState) GetUID() OptInt64 {
	return s.UID
}

// GetNickname returns the value of Nickname.
func (s *UserState) GetNickname() OptString {
	return s.Nickname
}

// GetExp returns the value of Exp.
func (s *UserState) GetExp() OptInt64 {
	return s.Exp
}

// GetLives returns the value of Lives.
func (s *UserState) GetLives() OptInt64 {
	return s.Lives
}

// GetGameID returns the value of GameID.
func (s *UserState) GetGameID() OptInt32 {
	return s.GameID
}

// GetFlags returns the value of Flags.
func (s *UserState) GetFlags() OptInt64 {
	return s.Flags
}

// SetUID sets the value of UID.
func (s *UserState) SetUID(val OptInt64) {
	s.UID = val
}

// SetNickname sets the value of Nickname.
func (s *UserState) SetNickname(val OptString) {
	s.Nickname = val
}

// SetExp sets the value of Exp.
func (s *UserState) SetExp(val OptInt64) {
	s.Exp = val
}

// SetLives sets the value of Lives.
func (s *UserState) SetLives(val OptInt64) {
	s.Lives = val
}

// SetGameID sets the value of GameID.
func (s *UserState) SetGameID(val OptInt32) {
	s.GameID = val
}

// SetFlags sets the value of Flags.
func (s *UserState) SetFlags(val OptInt64) {
	s.Flags = val
}

func (*UserState) getUsersStateUIDRes() {}
