// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"github.com/google/uuid"
)

type APIKeyHeader struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyHeader) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyHeader) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyHeader) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyHeader) SetRoles(val []string) {
	s.Roles = val
}

type APIKeyQueryParam struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyQueryParam) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyQueryParam) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyQueryParam) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyQueryParam) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/AuthRequest
type AuthRequest struct {
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *AuthRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *AuthRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *AuthRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *AuthRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	Player OptPlayer `json:"player"`
}

// GetPlayer returns the value of Player.
func (s *AuthResponse) GetPlayer() OptPlayer {
	return s.Player
}

// SetPlayer sets the value of Player.
func (s *AuthResponse) SetPlayer(val OptPlayer) {
	s.Player = val
}

func (*AuthResponse) authRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// The HTTP response code.
	Status OptInt `json:"status"`
	// A human-readable explanation of the error.
	Message OptString `json:"message"`
	// Type of the error message.
	Type OptString `json:"type"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() OptInt {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() OptString {
	return s.Message
}

// GetType returns the value of Type.
func (s *ErrorResponse) GetType() OptString {
	return s.Type
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val OptInt) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetType sets the value of Type.
func (s *ErrorResponse) SetType(val OptString) {
	s.Type = val
}

func (*ErrorResponse) authRes()              {}
func (*ErrorResponse) getPlayerStateUIDRes() {}
func (*ErrorResponse) signupRes()            {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPlayer returns new OptPlayer with value set to v.
func NewOptPlayer(v Player) OptPlayer {
	return OptPlayer{
		Value: v,
		Set:   true,
	}
}

// OptPlayer is optional Player.
type OptPlayer struct {
	Value Player
	Set   bool
}

// IsSet returns true if OptPlayer was set.
func (o OptPlayer) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPlayer) Reset() {
	var v Player
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPlayer) SetTo(v Player) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPlayer) Get() (v Player, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPlayer) Or(d Player) Player {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Player
type Player struct {
	// Player's ID in the system.
	UID OptUUID `json:"uid"`
	// Player's first name.
	Firstname OptString `json:"firstname"`
	// Player's last name.
	Lastname OptString `json:"lastname"`
	// Player's session ID.
	Sid OptString `json:"sid"`
	// Player's API Key that the client needs to provide when making API calls.
	Key OptString `json:"key"`
}

// GetUID returns the value of UID.
func (s *Player) GetUID() OptUUID {
	return s.UID
}

// GetFirstname returns the value of Firstname.
func (s *Player) GetFirstname() OptString {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *Player) GetLastname() OptString {
	return s.Lastname
}

// GetSid returns the value of Sid.
func (s *Player) GetSid() OptString {
	return s.Sid
}

// GetKey returns the value of Key.
func (s *Player) GetKey() OptString {
	return s.Key
}

// SetUID sets the value of UID.
func (s *Player) SetUID(val OptUUID) {
	s.UID = val
}

// SetFirstname sets the value of Firstname.
func (s *Player) SetFirstname(val OptString) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *Player) SetLastname(val OptString) {
	s.Lastname = val
}

// SetSid sets the value of Sid.
func (s *Player) SetSid(val OptString) {
	s.Sid = val
}

// SetKey sets the value of Key.
func (s *Player) SetKey(val OptString) {
	s.Key = val
}

// Ref: #/components/schemas/PlayerState
type PlayerState struct {
	// Player's ID in the system.
	UID OptUUID `json:"uid"`
	// Generated nickname in the system.
	Nickname OptString `json:"nickname"`
	// Player's exp points in the system.
	Exp OptInt64 `json:"exp"`
	// Player's lives count in the system.
	Lives OptInt64 `json:"lives"`
	// Some Player's flags.
	Flags OptInt64 `json:"flags"`
	// Game's ID (if game_id == 0 or absent then user in the lobby).
	GameID OptUUID `json:"game_id"`
}

// GetUID returns the value of UID.
func (s *PlayerState) GetUID() OptUUID {
	return s.UID
}

// GetNickname returns the value of Nickname.
func (s *PlayerState) GetNickname() OptString {
	return s.Nickname
}

// GetExp returns the value of Exp.
func (s *PlayerState) GetExp() OptInt64 {
	return s.Exp
}

// GetLives returns the value of Lives.
func (s *PlayerState) GetLives() OptInt64 {
	return s.Lives
}

// GetFlags returns the value of Flags.
func (s *PlayerState) GetFlags() OptInt64 {
	return s.Flags
}

// GetGameID returns the value of GameID.
func (s *PlayerState) GetGameID() OptUUID {
	return s.GameID
}

// SetUID sets the value of UID.
func (s *PlayerState) SetUID(val OptUUID) {
	s.UID = val
}

// SetNickname sets the value of Nickname.
func (s *PlayerState) SetNickname(val OptString) {
	s.Nickname = val
}

// SetExp sets the value of Exp.
func (s *PlayerState) SetExp(val OptInt64) {
	s.Exp = val
}

// SetLives sets the value of Lives.
func (s *PlayerState) SetLives(val OptInt64) {
	s.Lives = val
}

// SetFlags sets the value of Flags.
func (s *PlayerState) SetFlags(val OptInt64) {
	s.Flags = val
}

// SetGameID sets the value of GameID.
func (s *PlayerState) SetGameID(val OptUUID) {
	s.GameID = val
}

func (*PlayerState) getPlayerStateUIDRes() {}

// Ref: #/components/schemas/SignupRequest
type SignupRequest struct {
	// User's first name.
	Firstname string `json:"firstname"`
	// User's last name.
	Lastname string `json:"lastname"`
	// User's email.
	Email string `json:"email"`
	// User's password.
	Password string `json:"password"`
}

// GetFirstname returns the value of Firstname.
func (s *SignupRequest) GetFirstname() string {
	return s.Firstname
}

// GetLastname returns the value of Lastname.
func (s *SignupRequest) GetLastname() string {
	return s.Lastname
}

// GetEmail returns the value of Email.
func (s *SignupRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignupRequest) GetPassword() string {
	return s.Password
}

// SetFirstname sets the value of Firstname.
func (s *SignupRequest) SetFirstname(val string) {
	s.Firstname = val
}

// SetLastname sets the value of Lastname.
func (s *SignupRequest) SetLastname(val string) {
	s.Lastname = val
}

// SetEmail sets the value of Email.
func (s *SignupRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignupRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/SignupResponse
type SignupResponse struct {
	User OptPlayer `json:"user"`
}

// GetUser returns the value of User.
func (s *SignupResponse) GetUser() OptPlayer {
	return s.User
}

// SetUser sets the value of User.
func (s *SignupResponse) SetUser(val OptPlayer) {
	s.User = val
}

func (*SignupResponse) signupRes() {}
