// Code generated by ogen, DO NOT EDIT.

package baldaapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AcceptEndGame implements acceptEndGame operation.
	//
	// The opponent accepts the end-game proposal. The game ends immediately with
	// the current scores. Only the non-proposing player may call this.
	//
	// POST /games/{id}/accept-end
	AcceptEndGame(ctx context.Context, params AcceptEndGameParams) (AcceptEndGameRes, error)
	// Auth implements auth operation.
	//
	// Auth request.
	//
	// POST /auth
	Auth(ctx context.Context, req *AuthRequest) (AuthRes, error)
	// CreateGame implements createGame operation.
	//
	// Create a new game.
	//
	// POST /games
	CreateGame(ctx context.Context, params CreateGameParams) (CreateGameRes, error)
	// GetPlayerStateUID implements getPlayerStateUID operation.
	//
	// Get user state.
	//
	// GET /player/state/{uid}
	GetPlayerStateUID(ctx context.Context, params GetPlayerStateUIDParams) (GetPlayerStateUIDRes, error)
	// JoinGame implements joinGame operation.
	//
	// Adds the authenticated player to the specified waiting game.
	// When the second player joins (quorum of 2 is reached) the game
	// transitions to in_progress and the first move belongs to the
	// player who created the game.
	//
	// POST /games/{id}/join
	JoinGame(ctx context.Context, params JoinGameParams) (JoinGameRes, error)
	// ListGames implements listGames operation.
	//
	// Returns a snapshot of all currently active games.
	//
	// GET /games
	ListGames(ctx context.Context, params ListGamesParams) (ListGamesRes, error)
	// MoveGame implements moveGame operation.
	//
	// Places a new letter on the board and submits a word. If the word is valid,
	// the player's score is updated and the turn passes to the opponent.
	//
	// POST /games/{id}/move
	MoveGame(ctx context.Context, req *MoveRequest, params MoveGameParams) (MoveGameRes, error)
	// Ping implements ping operation.
	//
	// POST not GET — mutates session TTL.
	// Returns 204 with X-Server-Time header instead of a JSON body
	// to minimize bandwidth on frequent pings (every ping_delay ms).
	//
	// POST /session/ping
	Ping(ctx context.Context, params PingParams) (PingRes, error)
	// ProposeEndGame implements proposeEndGame operation.
	//
	// The current player proposes to end the game (e.g. no valid moves are available).
	// The turn timer is paused until the opponent responds.
	// Only the player whose turn it currently is may call this.
	//
	// POST /games/{id}/propose-end
	ProposeEndGame(ctx context.Context, params ProposeEndGameParams) (ProposeEndGameRes, error)
	// RejectEndGame implements rejectEndGame operation.
	//
	// The opponent rejects the end-game proposal. The game resumes with the
	// remaining turn time (minimum 10 seconds). Only the non-proposing player may call this.
	//
	// POST /games/{id}/reject-end
	RejectEndGame(ctx context.Context, params RejectEndGameParams) (RejectEndGameRes, error)
	// Signup implements signup operation.
	//
	// Sign-up request.
	//
	// POST /signup
	Signup(ctx context.Context, req *SignupRequest) (SignupRes, error)
	// SkipGame implements skipGame operation.
	//
	// Ends the current turn without making a move. The turn passes to the opponent.
	//
	// POST /games/{id}/skip
	SkipGame(ctx context.Context, params SkipGameParams) (SkipGameRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
